### ISSUE TITLE
Pipeline fails if deploy token secret doesn't already exist

### ISSUE THREAD

**Issue by GitBytes** [pnnl-miscscripts/gitlab-lib#2]
@kfox1111 I think there is a "chicken and egg" issue to work out here. This block seems to fail if the secret doesn't already exist:

### Current Code
https://github.com/pnnl-miscscripts/gitlab-lib/blob/9db5170a3bbd49ef7f9d008fd0051f54837e1806/gitlab-lib.yaml#L122-L124

### Current Output
```
$ SECRET_NAME="${SECRET_NAME:-gitlab-registry-token}" # collapsed multi-line command
Error from server (NotFound): secrets "config-editor-deploy-token" not found
error: flag docker-username is required
See 'kubectl create secret docker-registry -h' for help and examples
```

### Proposed Solution
I would propose something more like:
```yaml
    script:
    - |
      SECRET_NAME="${SECRET_NAME:-gitlab-registry-token}"
      kubectl create secret docker-registry "$SECRET_NAME" --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD" --docker-email=gitab@blackhole.com  --dry-run -o yaml | kubectl apply -f -
```

**Comment by GitBytes** [comment]
Closing as duplicate of #1

**Comment by kfox1111** [comment]
hmm... the 'Error from server (NotFound): secrets "config-editor-deploy-token" not found' is not really a problem. if keeping the code as is, it should probably be 2>/dev/null as its doing the create if its not found. I like your apply trick more though.

As for the real error, its saying docker-username is required but not specified. only way its hitting that is if $CI_DEPLOY_USER is not specified. I think this happens if you don't precreate the access token in gitlab?

**Comment by GitBytes** [comment]
@kfox1111 Sorry for the confusion on issues.. the UI messed up and created a duplicate issue (i.e. #2), so I closed it as dup. Please see #1 for the current issue or #3 for current PR
